{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "configurables",
    "version": "0.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.14.aar",
          "url": "configurables-0.0.14.aar",
          "size": 927008,
          "sha512": "769a6835d2007091a3ee0ef55389021f0d539a1cd3c1c72d1ff3feb2b97f6402b949df5becb07943a9cbeb83779a80e48d3eae069c0ac69e9f7b139cb7fe999b",
          "sha256": "2557db33ca6ea345c3c417a19d27bcfaf0bfd7f01a653f646c9efbdbca70072b",
          "sha1": "0337c6afee03e31a89b1780357f17ac45040057c",
          "md5": "4faa60571065e9f93923fe765d652f8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.14.aar",
          "url": "configurables-0.0.14.aar",
          "size": 927008,
          "sha512": "769a6835d2007091a3ee0ef55389021f0d539a1cd3c1c72d1ff3feb2b97f6402b949df5becb07943a9cbeb83779a80e48d3eae069c0ac69e9f7b139cb7fe999b",
          "sha256": "2557db33ca6ea345c3c417a19d27bcfaf0bfd7f01a653f646c9efbdbca70072b",
          "sha1": "0337c6afee03e31a89b1780357f17ac45040057c",
          "md5": "4faa60571065e9f93923fe765d652f8e"
        }
      ]
    }
  ]
}
