{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "core",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.22.aar",
          "url": "core-0.0.22.aar",
          "size": 744446,
          "sha512": "a01ccdcd18d898f86af745ead903d28c358361c1a02a0b4a8985ee7e3823a6d23d6ab222f4eb745e69c0cb0f827b29f6fd4a2341918e41a4046d977faad866ac",
          "sha256": "f6263d6c8e604bb3ab73ab3df2d75d24f0a4ce38102b7bbe0e15ce1330b78a3f",
          "sha1": "1ea75ab24b3ef078c90d2077219d272b748bae28",
          "md5": "019250729db9d07872e805cbabd61a9a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.22.aar",
          "url": "core-0.0.22.aar",
          "size": 744446,
          "sha512": "a01ccdcd18d898f86af745ead903d28c358361c1a02a0b4a8985ee7e3823a6d23d6ab222f4eb745e69c0cb0f827b29f6fd4a2341918e41a4046d977faad866ac",
          "sha256": "f6263d6c8e604bb3ab73ab3df2d75d24f0a4ce38102b7bbe0e15ce1330b78a3f",
          "sha1": "1ea75ab24b3ef078c90d2077219d272b748bae28",
          "md5": "019250729db9d07872e805cbabd61a9a"
        }
      ]
    }
  ]
}
