{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "core",
    "version": "0.0.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.22.aar",
          "url": "core-0.0.22.aar",
          "size": 744457,
          "sha512": "38cf90fe648a13aa954f8d51332e4024ae21738ab3d3e4bd7ba33af40befdc252d34b401059ec979d7490ecf98dac4684ec33388a24a85145e4a5e2308787c6c",
          "sha256": "d31da6488a67c46ac1e0ad7591f81e9e28a17a3e04daab9ae7ae61c757b65a7f",
          "sha1": "4b88d7ce8ea21d4372c328b8c01096cfa664cd57",
          "md5": "c41186dc11b4b9e51ff0148f84078095"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.22.aar",
          "url": "core-0.0.22.aar",
          "size": 744457,
          "sha512": "38cf90fe648a13aa954f8d51332e4024ae21738ab3d3e4bd7ba33af40befdc252d34b401059ec979d7490ecf98dac4684ec33388a24a85145e4a5e2308787c6c",
          "sha256": "d31da6488a67c46ac1e0ad7591f81e9e28a17a3e04daab9ae7ae61c757b65a7f",
          "sha1": "4b88d7ce8ea21d4372c328b8c01096cfa664cd57",
          "md5": "c41186dc11b4b9e51ff0148f84078095"
        }
      ]
    }
  ]
}
