{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "dev",
    "version": "1.1.0-dev1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dev-1.1.0-dev1.aar",
          "url": "dev-1.1.0-dev1.aar",
          "size": 106255,
          "sha512": "eb1757cc54f4b4fd7a0f0a0ef9919715ac6684232a342ae7101360c1ff8da920396f40ea2fc20714b6a81387dc6dccfad5a4d242ef4a5582d26b8c638ade28c6",
          "sha256": "55c567278c954c5ddbbc094579c329781bda8be30c5bf1d09b70edb912dfefac",
          "sha1": "84a0a7f728e94c698d6fc549f05eaa5a3f7477df",
          "md5": "0161dbb1ce8319ed7e24fda1358083e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "dev-1.1.0-dev1.aar",
          "url": "dev-1.1.0-dev1.aar",
          "size": 106255,
          "sha512": "eb1757cc54f4b4fd7a0f0a0ef9919715ac6684232a342ae7101360c1ff8da920396f40ea2fc20714b6a81387dc6dccfad5a4d242ef4a5582d26b8c638ade28c6",
          "sha256": "55c567278c954c5ddbbc094579c329781bda8be30c5bf1d09b70edb912dfefac",
          "sha1": "84a0a7f728e94c698d6fc549f05eaa5a3f7477df",
          "md5": "0161dbb1ce8319ed7e24fda1358083e0"
        }
      ]
    }
  ]
}
