{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-1.0.2.aar",
          "url": "pedro-1.0.2.aar",
          "size": 86599,
          "sha512": "3544abc99bd41f9408464e11fc594eb388debb13cea8b1bdda3c275a629928b8a75a28f51ad7c5c020072e216ef1364327460cf30fbbe11f849f7e614acc7f36",
          "sha256": "99e6e4baeeb5b08965dab60a0fa4d78706a5f2bed8eaa483413ce6198a8076e2",
          "sha1": "bce21f17224ad4f82c9d9239570e45ba47f8e52a",
          "md5": "51d49fb1146769b8fba6394dd60ccbd6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-1.0.2.aar",
          "url": "pedro-1.0.2.aar",
          "size": 86599,
          "sha512": "3544abc99bd41f9408464e11fc594eb388debb13cea8b1bdda3c275a629928b8a75a28f51ad7c5c020072e216ef1364327460cf30fbbe11f849f7e614acc7f36",
          "sha256": "99e6e4baeeb5b08965dab60a0fa4d78706a5f2bed8eaa483413ce6198a8076e2",
          "sha1": "bce21f17224ad4f82c9d9239570e45ba47f8e52a",
          "md5": "51d49fb1146769b8fba6394dd60ccbd6"
        }
      ]
    }
  ]
}
