{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "dev",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dev-1.0.2.aar",
          "url": "dev-1.0.2.aar",
          "size": 86633,
          "sha512": "82c2e00e00f81637140a24708e19c3c3d071acb30ec21cc168f558adba1f0b85a94a3f1ce49781b46fa884d786dc73d2313b90f8de4a70a13613372b03c78994",
          "sha256": "c23a59b067516f1f23484dcaafa47036eaf1f5a5934939d59af9e47bc9af2a58",
          "sha1": "1ca664d478138fbae293f4c660a039233d001645",
          "md5": "57d632be5b7ad4789a5f78555aeb6dda"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "dev-1.0.2.aar",
          "url": "dev-1.0.2.aar",
          "size": 86633,
          "sha512": "82c2e00e00f81637140a24708e19c3c3d071acb30ec21cc168f558adba1f0b85a94a3f1ce49781b46fa884d786dc73d2313b90f8de4a70a13613372b03c78994",
          "sha256": "c23a59b067516f1f23484dcaafa47036eaf1f5a5934939d59af9e47bc9af2a58",
          "sha1": "1ca664d478138fbae293f4c660a039233d001645",
          "md5": "57d632be5b7ad4789a5f78555aeb6dda"
        }
      ]
    }
  ]
}
