{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "fullpanels",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pedropathing.panels",
          "module": "core",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "telemetry",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "configurables",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "themes",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "capture",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "gamepad",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "field",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "docs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "battery",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "utils",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "pinger",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.40.aar",
          "url": "fullpanels-0.0.40.aar",
          "size": 260566,
          "sha512": "6491bc7e01617a90138b1fb2ff3ad7aa133367a3eeca8958f4db504acdf361590f61d54d862bb0f8a1572689cf6b2e3b9e2824711a57095b573e8f65dd6a958f",
          "sha256": "f94e507c0d87d1704e30d362b7854608d709d82c4e82fca884d890fb1d2d9517",
          "sha1": "e5b7a9c26c114a08ca5d952ab214a01bc781ada1",
          "md5": "9cce5a6ceb9bf68cafcbb7e00738ffd6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pedropathing.panels",
          "module": "core",
          "version": {
            "requires": "0.0.22"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "telemetry",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "configurables",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "themes",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "capture",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "gamepad",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "field",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "docs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "battery",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "utils",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "pinger",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.40.aar",
          "url": "fullpanels-0.0.40.aar",
          "size": 260566,
          "sha512": "6491bc7e01617a90138b1fb2ff3ad7aa133367a3eeca8958f4db504acdf361590f61d54d862bb0f8a1572689cf6b2e3b9e2824711a57095b573e8f65dd6a958f",
          "sha256": "f94e507c0d87d1704e30d362b7854608d709d82c4e82fca884d890fb1d2d9517",
          "sha1": "e5b7a9c26c114a08ca5d952ab214a01bc781ada1",
          "md5": "9cce5a6ceb9bf68cafcbb7e00738ffd6"
        }
      ]
    }
  ]
}
