{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "fullpanels",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pedropathing.panels",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "telemetry",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "configurables",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "themes",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "capture",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "gamepad",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "field",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "docs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "battery",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "utils",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "pinger",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.40.aar",
          "url": "fullpanels-0.0.40.aar",
          "size": 260582,
          "sha512": "cfee00079bcc0c46fb61b733b2861e06fa4eb99280140b85656554c54cb92dc10142b544885c96b14372c22f06462063a1bc15f7cd833048467e86c0a1c3558a",
          "sha256": "c611efdb349a9afed8dcbeda3f4b7154f975aeedb1d7ac0ac1bd467a956dcd42",
          "sha1": "f4dba0789fc1978ccfd61d4676614e4d4b1bcc61",
          "md5": "2af3e0902b8e0fd0a2cb006a53b4f4c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pedropathing.panels",
          "module": "core",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "telemetry",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "configurables",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "themes",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "capture",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "gamepad",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "field",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "docs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "battery",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "utils",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "pinger",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.40.aar",
          "url": "fullpanels-0.0.40.aar",
          "size": 260582,
          "sha512": "cfee00079bcc0c46fb61b733b2861e06fa4eb99280140b85656554c54cb92dc10142b544885c96b14372c22f06462063a1bc15f7cd833048467e86c0a1c3558a",
          "sha256": "c611efdb349a9afed8dcbeda3f4b7154f975aeedb1d7ac0ac1bd467a956dcd42",
          "sha1": "f4dba0789fc1978ccfd61d4676614e4d4b1bcc61",
          "md5": "2af3e0902b8e0fd0a2cb006a53b4f4c6"
        }
      ]
    }
  ]
}
