{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "fullpanels",
    "version": "0.0.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "panels",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "telemetry",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "configurables",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "themes",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "capture",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "gamepad",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "field",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "docs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "battery",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "utils",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "pinger",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.40.aar",
          "url": "fullpanels-0.0.40.aar",
          "size": 261253,
          "sha512": "51bed8a3ecf6e28cad5f740fed2f1d08f7b51431994c40d74384ac6d23cbb979b4d2062b68f331034f6bef0352c140e5d4a5e0d754bcef6eee65e3acec9165e8",
          "sha256": "ff22bba581bbe13bc88f25a2127e9e4b45fafa023f53d3d5adb0b5d79defd0c1",
          "sha1": "82129f14d63b024ad659e6ab9762fb5504ae107b",
          "md5": "1c5f09ebda9ab290427fd3d525a55f75"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "panels",
          "version": {
            "requires": "0.0.21"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "opmodecontrol",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "telemetry",
          "version": {
            "requires": "0.0.8"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "configurables",
          "version": {
            "requires": "0.0.14"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "themes",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "capture",
          "version": {
            "requires": "0.0.9"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "limelightproxy",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "gamepad",
          "version": {
            "requires": "0.0.13"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "field",
          "version": {
            "requires": "0.0.11"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "docs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "battery",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "utils",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "com.pedropathing.panels",
          "module": "pinger",
          "version": {
            "requires": "0.0.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "fullpanels-0.0.40.aar",
          "url": "fullpanels-0.0.40.aar",
          "size": 261253,
          "sha512": "51bed8a3ecf6e28cad5f740fed2f1d08f7b51431994c40d74384ac6d23cbb979b4d2062b68f331034f6bef0352c140e5d4a5e0d754bcef6eee65e3acec9165e8",
          "sha256": "ff22bba581bbe13bc88f25a2127e9e4b45fafa023f53d3d5adb0b5d79defd0c1",
          "sha1": "82129f14d63b024ad659e6ab9762fb5504ae107b",
          "md5": "1c5f09ebda9ab290427fd3d525a55f75"
        }
      ]
    }
  ]
}
