{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "core",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.23.aar",
          "url": "core-0.0.23.aar",
          "size": 744447,
          "sha512": "97edaa68d7a188e50e10f5be534123bef688996d041d7fc6e19517abd9cbfeef4b20430fa2881da8bc67e90782fbac62105387158eb2192e0dcae6334fbe38b9",
          "sha256": "7d671675fa4616d61329626cbaee5b9921a484ae84de7735434f7a7c2bba78d8",
          "sha1": "c2275980f03cfa711f20422f4e32b1f6486e7121",
          "md5": "7dce6c413bfb7bfe2bebd784ea8c2c6c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.23.aar",
          "url": "core-0.0.23.aar",
          "size": 744447,
          "sha512": "97edaa68d7a188e50e10f5be534123bef688996d041d7fc6e19517abd9cbfeef4b20430fa2881da8bc67e90782fbac62105387158eb2192e0dcae6334fbe38b9",
          "sha256": "7d671675fa4616d61329626cbaee5b9921a484ae84de7735434f7a7c2bba78d8",
          "sha1": "c2275980f03cfa711f20422f4e32b1f6486e7121",
          "md5": "7dce6c413bfb7bfe2bebd784ea8c2c6c"
        }
      ]
    }
  ]
}
