{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "core",
    "version": "0.0.23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.23.aar",
          "url": "core-0.0.23.aar",
          "size": 744435,
          "sha512": "1bb1a7629107197a992554175b448c5c52ba189124706ab3f115e1d21d341dd8433f80442fe6062458648c91988a60c7fbfa6c02dcf8bdcd4f7321f536a133ee",
          "sha256": "a8b935ce1baca35875409eb65c35ccd678380403ca1013125ef3b9c709742d39",
          "sha1": "87b04936e672b1480a4b634f9d31d72ea5a61a7a",
          "md5": "20c2e852deaf71b4febe25f0e49fd633"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.23.aar",
          "url": "core-0.0.23.aar",
          "size": 744435,
          "sha512": "1bb1a7629107197a992554175b448c5c52ba189124706ab3f115e1d21d341dd8433f80442fe6062458648c91988a60c7fbfa6c02dcf8bdcd4f7321f536a133ee",
          "sha256": "a8b935ce1baca35875409eb65c35ccd678380403ca1013125ef3b9c709742d39",
          "sha1": "87b04936e672b1480a4b634f9d31d72ea5a61a7a",
          "md5": "20c2e852deaf71b4febe25f0e49fd633"
        }
      ]
    }
  ]
}
