{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "configurables",
    "version": "0.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.15.aar",
          "url": "configurables-0.0.15.aar",
          "size": 926992,
          "sha512": "28b59a973d632172b5e063e5b2333a3397fac7b9eebde94db9749102fa981ea06de1a5fd82700cfb31a167cfa3523332f0442e873c31bfc6a1be87b1f07f03d0",
          "sha256": "ed7b6afdf05eef0dc5626cbafca94f118f7ae778c844ed68de3cd232b7972252",
          "sha1": "17a7a2e0bb45e709508b93cc92c3dd1b6cd65f46",
          "md5": "4b4b46e63b708cae8ce5ffa5f778fb1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "configurables-0.0.15.aar",
          "url": "configurables-0.0.15.aar",
          "size": 926992,
          "sha512": "28b59a973d632172b5e063e5b2333a3397fac7b9eebde94db9749102fa981ea06de1a5fd82700cfb31a167cfa3523332f0442e873c31bfc6a1be87b1f07f03d0",
          "sha256": "ed7b6afdf05eef0dc5626cbafca94f118f7ae778c844ed68de3cd232b7972252",
          "sha1": "17a7a2e0bb45e709508b93cc92c3dd1b6cd65f46",
          "md5": "4b4b46e63b708cae8ce5ffa5f778fb1b"
        }
      ]
    }
  ]
}
