{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "telemetry",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "telemetry-0.0.5.aar",
          "url": "telemetry-0.0.5.aar",
          "size": 9131,
          "sha512": "01c3e725f0f937a6eba09d7e68cd560447774fa53403105ff67841cc6a07e23a7048523460ee3e70321691bd14a295dcb8d59be20b34fb494913f3d418d0caf1",
          "sha256": "536823d45250a967b03069c60aff575f3f4b916f66679b42ec9c3bd6d564da31",
          "sha1": "9576c6aa96a046bd2f285bd08c7ad40b02fe0562",
          "md5": "4f7d0baa57d62c39ad1bb853c4ebd854"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.5.aar",
          "url": "telemetry-0.0.5.aar",
          "size": 9131,
          "sha512": "01c3e725f0f937a6eba09d7e68cd560447774fa53403105ff67841cc6a07e23a7048523460ee3e70321691bd14a295dcb8d59be20b34fb494913f3d418d0caf1",
          "sha256": "536823d45250a967b03069c60aff575f3f4b916f66679b42ec9c3bd6d564da31",
          "sha1": "9576c6aa96a046bd2f285bd08c7ad40b02fe0562",
          "md5": "4f7d0baa57d62c39ad1bb853c4ebd854"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "telemetry-0.0.5-sources.jar",
          "url": "telemetry-0.0.5-sources.jar",
          "size": 4776,
          "sha512": "ea0c7c89965e1794987e81d04a195f027b3ab450ff1c6bc4bab50230118af75df669c051bcb396268bd80e328deef1cffcbafb7423280d416d147cd5e8fa6da3",
          "sha256": "405bff4951b889ed2187220d4a1c9bdaff1eff3105a9eb88059d9ed9ea63e0ac",
          "sha1": "1a0f01af3f6e718300210a26a33a851a1e73cd7a",
          "md5": "d2a2dc9ef48b7c4f95b126628c4bf581"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "telemetry-0.0.5-javadoc.jar",
          "url": "telemetry-0.0.5-javadoc.jar",
          "size": 297798,
          "sha512": "3f438b9b37fec9a50a50999f5872639d3b3f17affef435b6775704c331e0091e20e8e8bd0d8c37a9fb2255b9785c8317745bda3319eeb57c8b7fa27156ff0e16",
          "sha256": "cf6f1c3e56806c5ee543a8395d785bde74bd4626cf4266cdc9d8458ef69332ec",
          "sha1": "094623c6db14911f915b630825fe86a056801be5",
          "md5": "720ddc4f1141197c310d727410f53b8f"
        }
      ]
    }
  ]
}
