{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "docs",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.7.aar",
          "url": "docs-0.0.7.aar",
          "size": 53325,
          "sha512": "24accfaee8b8c8610892d5966ddd818be334159384d185e86216a3e3db1b28295905d1bede466a7d10e61c135dbf5622c41e6476ba2f3d282bfa2f2b638e5813",
          "sha256": "85a49e4441fcc656f7611adceae404cc301929ac465d58dfb1d36779ff429db8",
          "sha1": "372d4f88f4bec6609c273a971f5b5998caa06c95",
          "md5": "a4595b1a20936a018cb65e7650e065ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.7.aar",
          "url": "docs-0.0.7.aar",
          "size": 53325,
          "sha512": "24accfaee8b8c8610892d5966ddd818be334159384d185e86216a3e3db1b28295905d1bede466a7d10e61c135dbf5622c41e6476ba2f3d282bfa2f2b638e5813",
          "sha256": "85a49e4441fcc656f7611adceae404cc301929ac465d58dfb1d36779ff429db8",
          "sha1": "372d4f88f4bec6609c273a971f5b5998caa06c95",
          "md5": "a4595b1a20936a018cb65e7650e065ce"
        }
      ]
    }
  ]
}
