{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "docs",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.7.aar",
          "url": "docs-0.0.7.aar",
          "size": 53309,
          "sha512": "28f45b706e71d318ff104d31e57738330ba56b2b9875113ec80e5bf40f0ec46f068c7798a7e51e2dc99c80c3905d6f41f037661e0852e007c9daa6f093324b8c",
          "sha256": "d27e1e2d4420b076d262fc68beec9c08e8dff7348f416ca22972893ced9e07d8",
          "sha1": "557532961a663403291668c48f16e126390d6bb4",
          "md5": "1c22079fa12808cfb9f20578cab22aaf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "docs-0.0.7.aar",
          "url": "docs-0.0.7.aar",
          "size": 53309,
          "sha512": "28f45b706e71d318ff104d31e57738330ba56b2b9875113ec80e5bf40f0ec46f068c7798a7e51e2dc99c80c3905d6f41f037661e0852e007c9daa6f093324b8c",
          "sha256": "d27e1e2d4420b076d262fc68beec9c08e8dff7348f416ca22972893ced9e07d8",
          "sha1": "557532961a663403291668c48f16e126390d6bb4",
          "md5": "1c22079fa12808cfb9f20578cab22aaf"
        }
      ]
    }
  ]
}
