{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "dev",
    "version": "1.1.0-dev16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dev-1.1.0-dev16.aar",
          "url": "dev-1.1.0-dev16.aar",
          "size": 118300,
          "sha512": "6f8cbabfe029907382f3de5f0c2c2b785965a3a53252a5441daf4539975d6430e9de2adcc1f727d1767f668c28f6390a5bed3ab0899bb44de94395602687c381",
          "sha256": "f6548e916c9f9df7bd1f2f5aa4ba047d01ad9cb71e68a8fba41cd07a35ac087a",
          "sha1": "978a43c421a0a1eecf0fa5c0be360d4e328d116e",
          "md5": "99104b3bb3567030601fd870abca91d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "dev-1.1.0-dev16.aar",
          "url": "dev-1.1.0-dev16.aar",
          "size": 118300,
          "sha512": "6f8cbabfe029907382f3de5f0c2c2b785965a3a53252a5441daf4539975d6430e9de2adcc1f727d1767f668c28f6390a5bed3ab0899bb44de94395602687c381",
          "sha256": "f6548e916c9f9df7bd1f2f5aa4ba047d01ad9cb71e68a8fba41cd07a35ac087a",
          "sha1": "978a43c421a0a1eecf0fa5c0be360d4e328d116e",
          "md5": "99104b3bb3567030601fd870abca91d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dev-1.1.0-dev16-sources.jar",
          "url": "dev-1.1.0-dev16-sources.jar",
          "size": 104732,
          "sha512": "9a90f198e74d5e7b1db20172b405604da0b4851cb3acbc047b7ddb2513672db65d397ff89437ccef7a49ae85f39407368876ae0585a0c79f459a2a6e307704d8",
          "sha256": "f5bac699c91da51b5a23c6244d7a38d261531dadec996d8bff5d1f092224c4b0",
          "sha1": "ff1a342477150c4e6ad01e9d5a92749c71aa2d58",
          "md5": "887d487b52b4ff39303f5709115f4a44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dev-1.1.0-dev16-javadoc.jar",
          "url": "dev-1.1.0-dev16-javadoc.jar",
          "size": 655593,
          "sha512": "1f2ba980699d661cb7f30fc4d172769eecb72c28e52a1c6edf7bab313330ed02dba3d3786ee3a417b382dfac9f34dc87e3f0ccf4c4c532cd1d554aabd862264e",
          "sha256": "0e68cc74a37ec6a84741d4714a9fefe8af48e207b066bbb1702d1976aee6e12b",
          "sha1": "60f79c372f9287508d2daff72440621945c03e2d",
          "md5": "5eab3fa0afd23bec2354d946765e75e7"
        }
      ]
    }
  ]
}
