{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "0.0.1-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-0.0.1-beta1.aar",
          "url": "pedro-0.0.1-beta1.aar",
          "size": 112899,
          "sha512": "ad8f9d89a72a8b0ce7593cef92c1db21b51f35297e92cb5c05f416368e8597a31a7e91fac2a50b89ad8a19aa126dbe530e1989966ba5230472b23eec2bf86acb",
          "sha256": "967e648732ada2d22c7c085c78d268a7b86daa1e00c76dc491245ac05ceab62f",
          "sha1": "c4986d7577d87a2442aa9706bdefff19e3d936d3",
          "md5": "4b2315811a7020cb6569b44c519048f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.0.1-beta1.aar",
          "url": "pedro-0.0.1-beta1.aar",
          "size": 112899,
          "sha512": "ad8f9d89a72a8b0ce7593cef92c1db21b51f35297e92cb5c05f416368e8597a31a7e91fac2a50b89ad8a19aa126dbe530e1989966ba5230472b23eec2bf86acb",
          "sha256": "967e648732ada2d22c7c085c78d268a7b86daa1e00c76dc491245ac05ceab62f",
          "sha1": "c4986d7577d87a2442aa9706bdefff19e3d936d3",
          "md5": "4b2315811a7020cb6569b44c519048f9"
        }
      ]
    }
  ]
}
