{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "core",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-1.1.0-SNAPSHOT.jar",
          "url": "core-1.1.0-SNAPSHOT.jar",
          "size": 88423,
          "sha512": "2c17bfb9d3a0236d21f57bfe6df90e9a3fefa4435c2f946c21377ba052c87919397af85579a2fbd7eca1335d339f6c9afef84fc45a1039f6dfe867f9305a68a9",
          "sha256": "a2b857275adcc5c074774b83335a1d119736524eb8f9f37f9a6ae57590f96cd5",
          "sha1": "feeeedc1a1b5f663e5d9562d056f9c2aac7bde4f",
          "md5": "9adac53a83cec3717f484ed3fc99f316"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.1.0-SNAPSHOT.jar",
          "url": "core-1.1.0-SNAPSHOT.jar",
          "size": 88423,
          "sha512": "2c17bfb9d3a0236d21f57bfe6df90e9a3fefa4435c2f946c21377ba052c87919397af85579a2fbd7eca1335d339f6c9afef84fc45a1039f6dfe867f9305a68a9",
          "sha256": "a2b857275adcc5c074774b83335a1d119736524eb8f9f37f9a6ae57590f96cd5",
          "sha1": "feeeedc1a1b5f663e5d9562d056f9c2aac7bde4f",
          "md5": "9adac53a83cec3717f484ed3fc99f316"
        }
      ]
    }
  ]
}
