{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "core",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-1.1.0-SNAPSHOT.jar",
          "url": "core-1.1.0-SNAPSHOT.jar",
          "size": 88443,
          "sha512": "fc1923dc7dec90add70181f406e0fdd710e580635baf331dc268688fd6dd9f1e95378efdde18aae658689a2b3dcfc79578c7716414c5ac6bfcc5814a14277320",
          "sha256": "555936e3fda57e50fff0961c6653cb1eedf3b3c5c8ed62a6dcbbf02cc986b9ed",
          "sha1": "66f7fd62b49bb67a805e9bde5c419672cc227c79",
          "md5": "a51439114c459b8e7c9355d05f51138f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.1.0-SNAPSHOT.jar",
          "url": "core-1.1.0-SNAPSHOT.jar",
          "size": 88443,
          "sha512": "fc1923dc7dec90add70181f406e0fdd710e580635baf331dc268688fd6dd9f1e95378efdde18aae658689a2b3dcfc79578c7716414c5ac6bfcc5814a14277320",
          "sha256": "555936e3fda57e50fff0961c6653cb1eedf3b3c5c8ed62a6dcbbf02cc986b9ed",
          "sha1": "66f7fd62b49bb67a805e9bde5c419672cc227c79",
          "md5": "a51439114c459b8e7c9355d05f51138f"
        }
      ]
    }
  ]
}
