{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "dev",
    "version": "1.1.0-dev13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dev-1.1.0-dev13.aar",
          "url": "dev-1.1.0-dev13.aar",
          "size": 117992,
          "sha512": "c1043379e2c2583f97bc07feff55c386ca3b602d3d1c817ed0b9555858385ed32d7a1a0daf6df5177759a82ade2440841f1df978226e5df24207575ac17821d0",
          "sha256": "f8f7d43f94714dbd513873bdf29993c28656e16af0143895a451b8b0e18d9999",
          "sha1": "f748d8befa1e8f6c0a09cd18f5c2079f9a841a8a",
          "md5": "7a28281fbad3c98ed9a6e0b727a331d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "dev-1.1.0-dev13.aar",
          "url": "dev-1.1.0-dev13.aar",
          "size": 117992,
          "sha512": "c1043379e2c2583f97bc07feff55c386ca3b602d3d1c817ed0b9555858385ed32d7a1a0daf6df5177759a82ade2440841f1df978226e5df24207575ac17821d0",
          "sha256": "f8f7d43f94714dbd513873bdf29993c28656e16af0143895a451b8b0e18d9999",
          "sha1": "f748d8befa1e8f6c0a09cd18f5c2079f9a841a8a",
          "md5": "7a28281fbad3c98ed9a6e0b727a331d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dev-1.1.0-dev13-sources.jar",
          "url": "dev-1.1.0-dev13-sources.jar",
          "size": 104551,
          "sha512": "9a839b95f7ae97215544ca8b267b8a3f8b17ea28cf4980c4f9d4b65e6b7cc2090afb10c118223ba8041387a339e1e3b76cea7adb0a5509d22b35f89fead85c2a",
          "sha256": "90f1b280a6cf9cb4468fd62a2863df788ae20f0edc5f5e8f11b622c60dc53d6d",
          "sha1": "6f5b2914d65e5b145d3fe6e6d0dc2462de603831",
          "md5": "61deacfeac3ef8709d23297b0a1decdc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dev-1.1.0-dev13-javadoc.jar",
          "url": "dev-1.1.0-dev13-javadoc.jar",
          "size": 654474,
          "sha512": "f9a0cc30a85a3e5972e88d4d8c4f6f4211e3b1800d2a4bf936eb609926cb781462fb8de9588cac8cb693be8cd4c2c4c80c664929191135dc56c9dc1a12cf62a4",
          "sha256": "1a507e9ec8b4b14a8ddd263ec9d90164304de62e9947b905097e195179f8b886",
          "sha1": "eed9d66e732bd7d280dbc5fd25c372d167d92bd3",
          "md5": "6ca604c2f2e156a44d0c79d4da26ce60"
        }
      ]
    }
  ]
}
