{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "field",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.13.aar",
          "url": "field-0.0.13.aar",
          "size": 1103628,
          "sha512": "4d5f15375d0f48fecc2ed572d3a6269f7d15ce810e2e62e0167d22f884e0fdc9262dcc00f99ba6e8ad98d030bc0b919c5f2c16d6f1393ad2b34230369a80ff99",
          "sha256": "1f33d61a9d0bf79a13c3e84a2398b3b4c1476b2f34402b2e79cedf655a7684ab",
          "sha1": "ac5ce17c4834df16a4c111b5eec40104d75208f5",
          "md5": "106fb4db8a7c31d9a12c773f245a5ae6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.13.aar",
          "url": "field-0.0.13.aar",
          "size": 1103628,
          "sha512": "4d5f15375d0f48fecc2ed572d3a6269f7d15ce810e2e62e0167d22f884e0fdc9262dcc00f99ba6e8ad98d030bc0b919c5f2c16d6f1393ad2b34230369a80ff99",
          "sha256": "1f33d61a9d0bf79a13c3e84a2398b3b4c1476b2f34402b2e79cedf655a7684ab",
          "sha1": "ac5ce17c4834df16a4c111b5eec40104d75208f5",
          "md5": "106fb4db8a7c31d9a12c773f245a5ae6"
        }
      ]
    }
  ]
}
