{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "telemetry",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.8.aar",
          "url": "telemetry-0.0.8.aar",
          "size": 444734,
          "sha512": "81264b686479766e219812c617150101b90f48bfa06df5d178bd18e07bc962f1223ec21354ace0d9743c7653cbab5a531faae262369dc49ad936edaf10c744d3",
          "sha256": "5886410ffd4b7f730b48f91e91c35a70833466ec1b5ef24379f3a37d5d0f1ef5",
          "sha1": "57e50bbac395c69e53ac22730dcc1b30037223ba",
          "md5": "b640192c5525194ea3b124dc07f6c8d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.8.aar",
          "url": "telemetry-0.0.8.aar",
          "size": 444734,
          "sha512": "81264b686479766e219812c617150101b90f48bfa06df5d178bd18e07bc962f1223ec21354ace0d9743c7653cbab5a531faae262369dc49ad936edaf10c744d3",
          "sha256": "5886410ffd4b7f730b48f91e91c35a70833466ec1b5ef24379f3a37d5d0f1ef5",
          "sha1": "57e50bbac395c69e53ac22730dcc1b30037223ba",
          "md5": "b640192c5525194ea3b124dc07f6c8d9"
        }
      ]
    }
  ]
}
