{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "0.0.1-beta14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-0.0.1-beta14.aar",
          "url": "pedro-0.0.1-beta14.aar",
          "size": 86384,
          "sha512": "7cda584b970fcb295f8f10de72b9799dc1d9e1065b6d4e06866b530119841adeca3697fbfb667b6046bc0989785cbe3968fa9e3e00cb3d4824472002ba1954d8",
          "sha256": "72d044a7a196da7ac67c2b4a4f33022e31d47836acfcf7cb0a6e82c2adb6ab6d",
          "sha1": "054f92397392c0ba3e84ca5ca89c165c77d44c3d",
          "md5": "fbee55df8986030f37e4bedf5426c06f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.0.1-beta14.aar",
          "url": "pedro-0.0.1-beta14.aar",
          "size": 86384,
          "sha512": "7cda584b970fcb295f8f10de72b9799dc1d9e1065b6d4e06866b530119841adeca3697fbfb667b6046bc0989785cbe3968fa9e3e00cb3d4824472002ba1954d8",
          "sha256": "72d044a7a196da7ac67c2b4a4f33022e31d47836acfcf7cb0a6e82c2adb6ab6d",
          "sha1": "054f92397392c0ba3e84ca5ca89c165c77d44c3d",
          "md5": "fbee55df8986030f37e4bedf5426c06f"
        }
      ]
    }
  ]
}
