{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "capture",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.9.aar",
          "url": "capture-0.0.9.aar",
          "size": 1602583,
          "sha512": "55118ab386a5c2079430a20d000118fdd3d555e730409da1eee1e6e5912e5141646504c214a592d05a9a87a4a33e0770a24373e8b8ab20c2edb53d2138fe5be6",
          "sha256": "18e7e8a9813cff4de2f9d920e17cd973b44698a85890027257ec5f218520f08c",
          "sha1": "d872b1e07d4b4f61a20f2c075143ff15658dca27",
          "md5": "d80af8f549c9bba3cd60de3cfe2ce8ad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.9.aar",
          "url": "capture-0.0.9.aar",
          "size": 1602583,
          "sha512": "55118ab386a5c2079430a20d000118fdd3d555e730409da1eee1e6e5912e5141646504c214a592d05a9a87a4a33e0770a24373e8b8ab20c2edb53d2138fe5be6",
          "sha256": "18e7e8a9813cff4de2f9d920e17cd973b44698a85890027257ec5f218520f08c",
          "sha1": "d872b1e07d4b4f61a20f2c075143ff15658dca27",
          "md5": "d80af8f549c9bba3cd60de3cfe2ce8ad"
        }
      ]
    }
  ]
}
