{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "capture",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.9.aar",
          "url": "capture-0.0.9.aar",
          "size": 1602599,
          "sha512": "d3c4c8d75067b2c171c431f7a1b632c55d00fce18838af990c595a5a75a0e79d239157dd115636b65101ed29160765cb7ceeecbb3eb462eda632f78be5f82704",
          "sha256": "0ee8bc0d6b9372d87e532962280faa046458f7fe05b2c8549dee71f5e84a8087",
          "sha1": "8766f4d18fd1ca5c19e093e25d3a3915bb91d594",
          "md5": "a9a7a3dff59427922f2b6dfc30af78e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "capture-0.0.9.aar",
          "url": "capture-0.0.9.aar",
          "size": 1602599,
          "sha512": "d3c4c8d75067b2c171c431f7a1b632c55d00fce18838af990c595a5a75a0e79d239157dd115636b65101ed29160765cb7ceeecbb3eb462eda632f78be5f82704",
          "sha256": "0ee8bc0d6b9372d87e532962280faa046458f7fe05b2c8549dee71f5e84a8087",
          "sha1": "8766f4d18fd1ca5c19e093e25d3a3915bb91d594",
          "md5": "a9a7a3dff59427922f2b6dfc30af78e3"
        }
      ]
    }
  ]
}
