{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "ftc",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "core",
          "version": {
            "requires": "1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOT.aar",
          "url": "ftc-1.1.0-SNAPSHOT.aar",
          "size": 37454,
          "sha512": "60e36b11f17ae2de6ec1ac34a15c9af80c5d7facec8fd79bde34bff4940548509978899c90e5b5a22ea3600d127eedae4615e438ab84a0598bc7893e456b871f",
          "sha256": "bbbd9cceabfe03bac5e381880b5b8e503524024f60acfce24134b6c99783c273",
          "sha1": "97e95baf67128b13bf342e7f5f6ce07f68e39804",
          "md5": "d976e004bbe7d98802547b2a4cb55e56"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "core",
          "version": {
            "requires": "1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOT.aar",
          "url": "ftc-1.1.0-SNAPSHOT.aar",
          "size": 37454,
          "sha512": "60e36b11f17ae2de6ec1ac34a15c9af80c5d7facec8fd79bde34bff4940548509978899c90e5b5a22ea3600d127eedae4615e438ab84a0598bc7893e456b871f",
          "sha256": "bbbd9cceabfe03bac5e381880b5b8e503524024f60acfce24134b6c99783c273",
          "sha1": "97e95baf67128b13bf342e7f5f6ce07f68e39804",
          "md5": "d976e004bbe7d98802547b2a4cb55e56"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOT-sources.jar",
          "url": "ftc-1.1.0-SNAPSHOT-sources.jar",
          "size": 33732,
          "sha512": "889808cb57bc516c6a4bbd14f70e115021e8f41084715e8f73435daff9026983e0a137cc52153f0fd5fff37bbde3381f9d05892ff3950891e31c39d36c120567",
          "sha256": "16cacd7442518ab1e770e0c04fbff63254de62934d87ca173f34f944040ddc03",
          "sha1": "984ba962c83778117872cf6f31846352212de5ca",
          "md5": "6e5db56628be8f2a1d2169e3715605f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOT-javadoc.jar",
          "url": "ftc-1.1.0-SNAPSHOT-javadoc.jar",
          "size": 401517,
          "sha512": "4f519f759c6455cc2470a4e15e5ceb3b79fd9f7a00d7f32a2eed89c6bbb8f8f38ab5cb7ff30446840cc3394ae18f50524c6e9c0ad4508061e8c0a17d38146c2d",
          "sha256": "2d9e6ece53cbd582cc195795fd369d61066e06ea8a8ec2b03db94bb6efb54544",
          "sha1": "65b7d7765a69a53ae8c81881990dd7567eaa6082",
          "md5": "8505b7c0340b55b43724a5af5e290bf2"
        }
      ]
    }
  ]
}
