{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "ftc",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "core",
          "version": {
            "requires": "1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOT.aar",
          "url": "ftc-1.1.0-SNAPSHOT.aar",
          "size": 37453,
          "sha512": "da55f545f5d024c64aab4840b50a623260ac440cd40235e1b3a928ccab5ae583999ecdf9a6c2f28c18e54d47ed089a857aedf6a350fe854c9bcc74e420a278b5",
          "sha256": "1ac1356eb259a6515ed48578b558f1c19540092041ef01c23b69f5b284df1faf",
          "sha1": "1f3ee6c412e85549c8459bad0997c9bfa438ef81",
          "md5": "c794fb0ad435d490f77bda0577020537"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "core",
          "version": {
            "requires": "1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOT.aar",
          "url": "ftc-1.1.0-SNAPSHOT.aar",
          "size": 37453,
          "sha512": "da55f545f5d024c64aab4840b50a623260ac440cd40235e1b3a928ccab5ae583999ecdf9a6c2f28c18e54d47ed089a857aedf6a350fe854c9bcc74e420a278b5",
          "sha256": "1ac1356eb259a6515ed48578b558f1c19540092041ef01c23b69f5b284df1faf",
          "sha1": "1f3ee6c412e85549c8459bad0997c9bfa438ef81",
          "md5": "c794fb0ad435d490f77bda0577020537"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOT-sources.jar",
          "url": "ftc-1.1.0-SNAPSHOT-sources.jar",
          "size": 33736,
          "sha512": "e59e196c489b786880cd2a7d6d998ea58ac46a94d0e06f35228f8781ee936b39222be0b2c20455f1d3d0b3a4dc202e527dad07b437faa40f4cab664cde5c517a",
          "sha256": "9767a6a53bdac68d031078092df208a0351a8b7c8a5c77c5d0b1742ec27b07d6",
          "sha1": "48b3e79d49300a57fd4b57686f1004103fc78c5f",
          "md5": "a2e96dd375d876b83250e1d998151e55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOT-javadoc.jar",
          "url": "ftc-1.1.0-SNAPSHOT-javadoc.jar",
          "size": 401517,
          "sha512": "4f519f759c6455cc2470a4e15e5ceb3b79fd9f7a00d7f32a2eed89c6bbb8f8f38ab5cb7ff30446840cc3394ae18f50524c6e9c0ad4508061e8c0a17d38146c2d",
          "sha256": "2d9e6ece53cbd582cc195795fd369d61066e06ea8a8ec2b03db94bb6efb54544",
          "sha1": "65b7d7765a69a53ae8c81881990dd7567eaa6082",
          "md5": "8505b7c0340b55b43724a5af5e290bf2"
        }
      ]
    }
  ]
}
