{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "exampleplugin",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.8.aar",
          "url": "exampleplugin-0.0.8.aar",
          "size": 55351,
          "sha512": "be51090b439713af0b3eabbd40cf699924a8af308ffe7497e35dd93b315f9817d7d6c94e1a025ed2abd300b03a6b9b17815762d9386c4b2f953ea73bb33e9fe1",
          "sha256": "7bdf8d61761de44ba8841be4347f1e078671755c2572245deab9052cd463c4c4",
          "sha1": "ff1a184151128893aad946692aaa6100bebec8f9",
          "md5": "eec6ba0f1003d81af2a3856274621555"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.8.aar",
          "url": "exampleplugin-0.0.8.aar",
          "size": 55351,
          "sha512": "be51090b439713af0b3eabbd40cf699924a8af308ffe7497e35dd93b315f9817d7d6c94e1a025ed2abd300b03a6b9b17815762d9386c4b2f953ea73bb33e9fe1",
          "sha256": "7bdf8d61761de44ba8841be4347f1e078671755c2572245deab9052cd463c4c4",
          "sha1": "ff1a184151128893aad946692aaa6100bebec8f9",
          "md5": "eec6ba0f1003d81af2a3856274621555"
        }
      ]
    }
  ]
}
