{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "exampleplugin",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.8.aar",
          "url": "exampleplugin-0.0.8.aar",
          "size": 55335,
          "sha512": "603c4dfd9f892311bfb7e3c8e7231cd8896dd1a2102b35ab6644b90136858b96f51a498b55695924163e77b66aeb3c07efea35249863aa709a49598e883f6d3b",
          "sha256": "e5b058f6c1fb8e52eee29cbe6f24811416e6e9ba46619203b0c30b22691dddf7",
          "sha1": "521e67c57d238630fa65997b740ea2ce57a71c3c",
          "md5": "79884bb46c585c6c6f22c6d0182f9735"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "exampleplugin-0.0.8.aar",
          "url": "exampleplugin-0.0.8.aar",
          "size": 55335,
          "sha512": "603c4dfd9f892311bfb7e3c8e7231cd8896dd1a2102b35ab6644b90136858b96f51a498b55695924163e77b66aeb3c07efea35249863aa709a49598e883f6d3b",
          "sha256": "e5b058f6c1fb8e52eee29cbe6f24811416e6e9ba46619203b0c30b22691dddf7",
          "sha1": "521e67c57d238630fa65997b740ea2ce57a71c3c",
          "md5": "79884bb46c585c6c6f22c6d0182f9735"
        }
      ]
    }
  ]
}
