{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "core",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.21.aar",
          "url": "core-0.0.21.aar",
          "size": 744449,
          "sha512": "88066e0e18a7b6494242e510a3116ddfe2746de1aa7c4798b8305f14a05219182a94459a7153ce786265d533ce66984354f70ecc4556e267c5d7f4ca5cbd69c4",
          "sha256": "0061078e7e9f4f61c8cf7086111d03a8b38b69652cd04365cf229609a01189b3",
          "sha1": "6447ee92ee5d719bfd11c1e15dc3c17c6731efab",
          "md5": "729652fdacf54daa193ac9ed37f3f0df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.0.21.aar",
          "url": "core-0.0.21.aar",
          "size": 744449,
          "sha512": "88066e0e18a7b6494242e510a3116ddfe2746de1aa7c4798b8305f14a05219182a94459a7153ce786265d533ce66984354f70ecc4556e267c5d7f4ca5cbd69c4",
          "sha256": "0061078e7e9f4f61c8cf7086111d03a8b38b69652cd04365cf229609a01189b3",
          "sha1": "6447ee92ee5d719bfd11c1e15dc3c17c6731efab",
          "md5": "729652fdacf54daa193ac9ed37f3f0df"
        }
      ]
    }
  ]
}
