{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "pinger",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.6.aar",
          "url": "pinger-0.0.6.aar",
          "size": 257402,
          "sha512": "f6283b3548dc7be3e0f0fc6f4b31cc551c74951464a9dd7aad4252668760ef89a3b19bb1763a653efdaf96bc7242ff234206a6d824534038973ff540643c920d",
          "sha256": "ba32e626c28e72e8752e166551f195dbea3bca4d32008a6b78cff0deb93ba708",
          "sha1": "d2ff4827004858f793ba2add7add870c9aa50ec8",
          "md5": "8502bd0c5094345301659fa91f6599f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.6.aar",
          "url": "pinger-0.0.6.aar",
          "size": 257402,
          "sha512": "f6283b3548dc7be3e0f0fc6f4b31cc551c74951464a9dd7aad4252668760ef89a3b19bb1763a653efdaf96bc7242ff234206a6d824534038973ff540643c920d",
          "sha256": "ba32e626c28e72e8752e166551f195dbea3bca4d32008a6b78cff0deb93ba708",
          "sha1": "d2ff4827004858f793ba2add7add870c9aa50ec8",
          "md5": "8502bd0c5094345301659fa91f6599f6"
        }
      ]
    }
  ]
}
