{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "pinger",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.6.aar",
          "url": "pinger-0.0.6.aar",
          "size": 257386,
          "sha512": "500d5f08206fdf907e76952feacf38e591ab049fb334203003c7c33c836dbaf1c05f4467977c80db375959b91e6fa97b04bdf84fe6a14b0def51bfb810826857",
          "sha256": "e288ad8b06ac879217b101827a57dce8aa4b397f64e8d81b3669ea15a325cb7b",
          "sha1": "93dd97cc2023c57b03cba3563acedd941b0ff0b7",
          "md5": "087367c8574de5e011614a08d5a6a411"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "pinger-0.0.6.aar",
          "url": "pinger-0.0.6.aar",
          "size": 257386,
          "sha512": "500d5f08206fdf907e76952feacf38e591ab049fb334203003c7c33c836dbaf1c05f4467977c80db375959b91e6fa97b04bdf84fe6a14b0def51bfb810826857",
          "sha256": "e288ad8b06ac879217b101827a57dce8aa4b397f64e8d81b3669ea15a325cb7b",
          "sha1": "93dd97cc2023c57b03cba3563acedd941b0ff0b7",
          "md5": "087367c8574de5e011614a08d5a6a411"
        }
      ]
    }
  ]
}
