{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "panels",
    "version": "0.0.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.21.aar",
          "url": "panels-0.0.21.aar",
          "size": 745127,
          "sha512": "e9279ad5ef72b832e3853f10b038fca7141d46c1ac7484f5127feed921bc826c32821bf43e170963149c75e0c7de479ca6104637bc71aee5dc5c4ee94ec7eab2",
          "sha256": "d952178115591b0566a1dc1eef025ac3d9f52b3953d423be93e04d489d731101",
          "sha1": "82b383b7f4324b3646b37419bde9e8134366c754",
          "md5": "d299c6d5cc9211350a5dc88123a5e7a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.nanohttpd",
          "module": "nanohttpd-websocket",
          "version": {
            "requires": "2.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "nanohttpd"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "panels-0.0.21.aar",
          "url": "panels-0.0.21.aar",
          "size": 745127,
          "sha512": "e9279ad5ef72b832e3853f10b038fca7141d46c1ac7484f5127feed921bc826c32821bf43e170963149c75e0c7de479ca6104637bc71aee5dc5c4ee94ec7eab2",
          "sha256": "d952178115591b0566a1dc1eef025ac3d9f52b3953d423be93e04d489d731101",
          "sha1": "82b383b7f4324b3646b37419bde9e8134366c754",
          "md5": "d299c6d5cc9211350a5dc88123a5e7a6"
        }
      ]
    }
  ]
}
