{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "battery",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.10.aar",
          "url": "battery-0.0.10.aar",
          "size": 945963,
          "sha512": "d3b381827aa3b40897d9418f79f07a4c45428aef4b980100fdeabdd44cce5fce668773a7c42270ce5d65761d01b324646b9f1d27b90449a71c1231f0fc05bc02",
          "sha256": "cb9ea2bcdd11b833396ac38c852af818905ba9de491f162930571f15ecc42224",
          "sha1": "919c4ccf5f7f30f94a97ccdbfa225bf14d02cd0d",
          "md5": "5ecf9259204aff94dc86f67c1713fc43"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.10.aar",
          "url": "battery-0.0.10.aar",
          "size": 945963,
          "sha512": "d3b381827aa3b40897d9418f79f07a4c45428aef4b980100fdeabdd44cce5fce668773a7c42270ce5d65761d01b324646b9f1d27b90449a71c1231f0fc05bc02",
          "sha256": "cb9ea2bcdd11b833396ac38c852af818905ba9de491f162930571f15ecc42224",
          "sha1": "919c4ccf5f7f30f94a97ccdbfa225bf14d02cd0d",
          "md5": "5ecf9259204aff94dc86f67c1713fc43"
        }
      ]
    }
  ]
}
