{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "battery",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.10.aar",
          "url": "battery-0.0.10.aar",
          "size": 945276,
          "sha512": "ed00d2b0cb19c4c6b2ed987d2875b1876beec32f4d8073c127eed641eead79afb064f670b3df6f2d3afc24358950ce11f1e7b7f7ae2a716418ee4f3d5ade4ec9",
          "sha256": "2255cdbe2f0cbed7914da726d73d118d4f8df012ce10766da2560c406d36e93e",
          "sha1": "14ce9c71b9a2649664dbad6b7f7b2c686c634a7b",
          "md5": "c0a6b9293859d05bf685ffc779af9423"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.10.aar",
          "url": "battery-0.0.10.aar",
          "size": 945276,
          "sha512": "ed00d2b0cb19c4c6b2ed987d2875b1876beec32f4d8073c127eed641eead79afb064f670b3df6f2d3afc24358950ce11f1e7b7f7ae2a716418ee4f3d5ade4ec9",
          "sha256": "2255cdbe2f0cbed7914da726d73d118d4f8df012ce10766da2560c406d36e93e",
          "sha1": "14ce9c71b9a2649664dbad6b7f7b2c686c634a7b",
          "md5": "c0a6b9293859d05bf685ffc779af9423"
        }
      ]
    }
  ]
}
