{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "battery",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.10.aar",
          "url": "battery-0.0.10.aar",
          "size": 945292,
          "sha512": "7d47f4ef6794c0da3a25f3b349632e50fb95fa1a837fe395c9eabbb323b7f7c27df9b7cfb86c78fced4d72a0476d0526cdece590050b86290be03c23681c4e11",
          "sha256": "b0dbd49553e054ec5fd080b865042e969e89db5c5dec8162bf7a0f7ed9f23d0d",
          "sha1": "9a43c7537ed47a73c9f5e8c68e886a529a8b4654",
          "md5": "cd5e40b435d4c6501ed7f649f0f831b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "battery-0.0.10.aar",
          "url": "battery-0.0.10.aar",
          "size": 945292,
          "sha512": "7d47f4ef6794c0da3a25f3b349632e50fb95fa1a837fe395c9eabbb323b7f7c27df9b7cfb86c78fced4d72a0476d0526cdece590050b86290be03c23681c4e11",
          "sha256": "b0dbd49553e054ec5fd080b865042e969e89db5c5dec8162bf7a0f7ed9f23d0d",
          "sha1": "9a43c7537ed47a73c9f5e8c68e886a529a8b4654",
          "md5": "cd5e40b435d4c6501ed7f649f0f831b6"
        }
      ]
    }
  ]
}
