{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-1.0.0.aar",
          "url": "pedro-1.0.0.aar",
          "size": 86402,
          "sha512": "cb8b620dae55b70e1c3691b0ebb7a6e922f2e6c027d8f0304e74eeedf255764a061ab1a3ac1e1f0a15d485036933d203e2c9e6c19597b410d7b192ddf0c5bdbb",
          "sha256": "2caeec63c18f3dab39b31ebfc2ad50ead10774f5c5e9c281c72e00d53cd16737",
          "sha1": "3fe1f58501347a6be9c94dac39ae8cce0e80fc4a",
          "md5": "a03a41026ff0fd27d51086b363226004"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-1.0.0.aar",
          "url": "pedro-1.0.0.aar",
          "size": 86402,
          "sha512": "cb8b620dae55b70e1c3691b0ebb7a6e922f2e6c027d8f0304e74eeedf255764a061ab1a3ac1e1f0a15d485036933d203e2c9e6c19597b410d7b192ddf0c5bdbb",
          "sha256": "2caeec63c18f3dab39b31ebfc2ad50ead10774f5c5e9c281c72e00d53cd16737",
          "sha1": "3fe1f58501347a6be9c94dac39ae8cce0e80fc4a",
          "md5": "a03a41026ff0fd27d51086b363226004"
        }
      ]
    }
  ]
}
