{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "dev",
    "version": "1.1.0-dev5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dev-1.1.0-dev5.aar",
          "url": "dev-1.1.0-dev5.aar",
          "size": 108919,
          "sha512": "dab9929a1fdba8b2c5703ac31dadbe2a62b4e492ca63f5d78ecd25c01b3a06981e5f999a16419ef934b1803f6cb3ea4a95510f77db5d58c1090d6d48b36860d5",
          "sha256": "c1f1038140d7f14a7735c00f5baa0067182fa76cb6e2183111bcf25ab67cd362",
          "sha1": "854b57d1da38aad4d4fbc589d78b1a1bedf98980",
          "md5": "e9c783c22316d10020500b455747e094"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-jvm",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "dev-1.1.0-dev5.aar",
          "url": "dev-1.1.0-dev5.aar",
          "size": 108919,
          "sha512": "dab9929a1fdba8b2c5703ac31dadbe2a62b4e492ca63f5d78ecd25c01b3a06981e5f999a16419ef934b1803f6cb3ea4a95510f77db5d58c1090d6d48b36860d5",
          "sha256": "c1f1038140d7f14a7735c00f5baa0067182fa76cb6e2183111bcf25ab67cd362",
          "sha1": "854b57d1da38aad4d4fbc589d78b1a1bedf98980",
          "md5": "e9c783c22316d10020500b455747e094"
        }
      ]
    }
  ]
}
