{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "limelightproxy",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.10.aar",
          "url": "limelightproxy-0.0.10.aar",
          "size": 494545,
          "sha512": "3cf998181660b1ee25ef4bf4d5a1fc1db708830400ae9b3b43ad6ca034332009d435052373cc003eb252136200774be2ab07d64406e0e012392b4ad1b9e9ead7",
          "sha256": "f01bbac26d1fc400e191a93acd45828198335da023962ed2ffad292aabc39e09",
          "sha1": "fe481368eb7b0a50005f8df347c46485268f451a",
          "md5": "5824bf9abb16bbdec761fc56f2564ddd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.10.aar",
          "url": "limelightproxy-0.0.10.aar",
          "size": 494545,
          "sha512": "3cf998181660b1ee25ef4bf4d5a1fc1db708830400ae9b3b43ad6ca034332009d435052373cc003eb252136200774be2ab07d64406e0e012392b4ad1b9e9ead7",
          "sha256": "f01bbac26d1fc400e191a93acd45828198335da023962ed2ffad292aabc39e09",
          "sha1": "fe481368eb7b0a50005f8df347c46485268f451a",
          "md5": "5824bf9abb16bbdec761fc56f2564ddd"
        }
      ]
    }
  ]
}
