{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "limelightproxy",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.10.aar",
          "url": "limelightproxy-0.0.10.aar",
          "size": 494561,
          "sha512": "646eb847cc8d5f8f300f8550633a928610e43f021d830816afd1dfde7d25ad9113727a1d89682e2eb9e8b4161e71c96519e0dc3b09ebfde8f0dfb31abac4b22f",
          "sha256": "d74dd388e9c6c56c1840bc5af3bc719ba1fcd391bf69c68a873ad685e0ce1128",
          "sha1": "fce5ffb54af87ed2900129d7a98ed8afa9081041",
          "md5": "6405f39268a4a6d49b52484d5ea0bd58"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "limelightproxy-0.0.10.aar",
          "url": "limelightproxy-0.0.10.aar",
          "size": 494561,
          "sha512": "646eb847cc8d5f8f300f8550633a928610e43f021d830816afd1dfde7d25ad9113727a1d89682e2eb9e8b4161e71c96519e0dc3b09ebfde8f0dfb31abac4b22f",
          "sha256": "d74dd388e9c6c56c1840bc5af3bc719ba1fcd391bf69c68a873ad685e0ce1128",
          "sha1": "fce5ffb54af87ed2900129d7a98ed8afa9081041",
          "md5": "6405f39268a4a6d49b52484d5ea0bd58"
        }
      ]
    }
  ]
}
