{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "themes",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.11.aar",
          "url": "themes-0.0.11.aar",
          "size": 1254230,
          "sha512": "9d5c180471b70ec276fe7fb4350f5e84788b6a8f2b70b5863f24be61526cb10d2f5e24434b1102ba1ef92a518f113b81a9b678ea5e4c191647eee7eb3c2e98e2",
          "sha256": "58672b27a7de8d01c0178b2600643d8cc95a64cd49fcda01cabfa0041d4f0efe",
          "sha1": "4572abaa3f81251526eed51bda0f99924ba9cac2",
          "md5": "bd5d4626ec690f228542116094ebc8e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.11.aar",
          "url": "themes-0.0.11.aar",
          "size": 1254230,
          "sha512": "9d5c180471b70ec276fe7fb4350f5e84788b6a8f2b70b5863f24be61526cb10d2f5e24434b1102ba1ef92a518f113b81a9b678ea5e4c191647eee7eb3c2e98e2",
          "sha256": "58672b27a7de8d01c0178b2600643d8cc95a64cd49fcda01cabfa0041d4f0efe",
          "sha1": "4572abaa3f81251526eed51bda0f99924ba9cac2",
          "md5": "bd5d4626ec690f228542116094ebc8e2"
        }
      ]
    }
  ]
}
