{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "themes",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.11.aar",
          "url": "themes-0.0.11.aar",
          "size": 1254246,
          "sha512": "b4d5dc3a8f84f121b45358ef111d8a3a9268c704f750a283f477cbf390bc327a39b9295601510c64b7ee0eca6c88833dde7996edfbde98dbe09b4c75f1b869d9",
          "sha256": "3090cf7485a7363054518fdee43af720bb2e5c14c1b55fd576f07abf1f06eb8a",
          "sha1": "fdad2930c224d92910899005aa57de73ae4db420",
          "md5": "4744b34eaf2c63913c38a087b294b641"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.11.aar",
          "url": "themes-0.0.11.aar",
          "size": 1254246,
          "sha512": "b4d5dc3a8f84f121b45358ef111d8a3a9268c704f750a283f477cbf390bc327a39b9295601510c64b7ee0eca6c88833dde7996edfbde98dbe09b4c75f1b869d9",
          "sha256": "3090cf7485a7363054518fdee43af720bb2e5c14c1b55fd576f07abf1f06eb8a",
          "sha1": "fdad2930c224d92910899005aa57de73ae4db420",
          "md5": "4744b34eaf2c63913c38a087b294b641"
        }
      ]
    }
  ]
}
