{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "themes",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.11.aar",
          "url": "themes-0.0.11.aar",
          "size": 1254917,
          "sha512": "bcc054b2cf4edfaa7eb698c1f46ce6f16955bff5785e19bf72e517ec05420b42813a2a1ddc1cd37112b8c11aefb54d34abbda1a58f4e3e434a5d16339e4c33e7",
          "sha256": "0591e7d55c96d2858ab8501403ab54c874ab2936be4eb3b9b960d1b2bfc4d5ef",
          "sha1": "831b0bf7e9edc8fede541af2ce8e8c18d291e53d",
          "md5": "45c744db7e23c2c779ef8829eaec35aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "themes-0.0.11.aar",
          "url": "themes-0.0.11.aar",
          "size": 1254917,
          "sha512": "bcc054b2cf4edfaa7eb698c1f46ce6f16955bff5785e19bf72e517ec05420b42813a2a1ddc1cd37112b8c11aefb54d34abbda1a58f4e3e434a5d16339e4c33e7",
          "sha256": "0591e7d55c96d2858ab8501403ab54c874ab2936be4eb3b9b960d1b2bfc4d5ef",
          "sha1": "831b0bf7e9edc8fede541af2ce8e8c18d291e53d",
          "md5": "45c744db7e23c2c779ef8829eaec35aa"
        }
      ]
    }
  ]
}
