{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "dev",
    "version": "1.0.6-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dev-1.0.6-beta1.aar",
          "url": "dev-1.0.6-beta1.aar",
          "size": 86518,
          "sha512": "a83fb089e759bdcb123cab5a4be042dd8f8553510eebd6d083f3abe8df92afc38b4b179f9544842a7ae2ea0d72d975643fbad3e6d0f7f7f7b8992b75ad4c2fce",
          "sha256": "ef2534d8cd609d4664d4d0998dca8046e85e6439d2be0f2e34c1b5b00055d08b",
          "sha1": "4ff70a49cc1f13913b30576bc3eff8a02a78f76f",
          "md5": "82f9307799201f0955dd79d27a0f49b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "dev-1.0.6-beta1.aar",
          "url": "dev-1.0.6-beta1.aar",
          "size": 86518,
          "sha512": "a83fb089e759bdcb123cab5a4be042dd8f8553510eebd6d083f3abe8df92afc38b4b179f9544842a7ae2ea0d72d975643fbad3e6d0f7f7f7b8992b75ad4c2fce",
          "sha256": "ef2534d8cd609d4664d4d0998dca8046e85e6439d2be0f2e34c1b5b00055d08b",
          "sha1": "4ff70a49cc1f13913b30576bc3eff8a02a78f76f",
          "md5": "82f9307799201f0955dd79d27a0f49b3"
        }
      ]
    }
  ]
}
