{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "beta",
    "version": "1.0.7-beta6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "beta-1.0.7-beta6.aar",
          "url": "beta-1.0.7-beta6.aar",
          "size": 88264,
          "sha512": "117fe2a4ae932d271c01b59f8641f86eff724e0bf0cf5d072845696f22801933368ffb046dac9e4077bc04767e2bd396df7166ceb6582e7dddba6916f2932ac1",
          "sha256": "bd7d058df2c804cf5f3cdbbf89bd735bf1d2376739755d5da641bf760c48efa7",
          "sha1": "d94bdca486b1a5d31a74beeab29659b6f653e304",
          "md5": "17a9b437169d0d155f156082b331bf03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "beta-1.0.7-beta6.aar",
          "url": "beta-1.0.7-beta6.aar",
          "size": 88264,
          "sha512": "117fe2a4ae932d271c01b59f8641f86eff724e0bf0cf5d072845696f22801933368ffb046dac9e4077bc04767e2bd396df7166ceb6582e7dddba6916f2932ac1",
          "sha256": "bd7d058df2c804cf5f3cdbbf89bd735bf1d2376739755d5da641bf760c48efa7",
          "sha1": "d94bdca486b1a5d31a74beeab29659b6f653e304",
          "md5": "17a9b437169d0d155f156082b331bf03"
        }
      ]
    }
  ]
}
