{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "gamepad",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.13.aar",
          "url": "gamepad-0.0.13.aar",
          "size": 8844630,
          "sha512": "3e70a580b5536084ea199a1b262c669c0189dab06dd3ae83f53b82fb1391206f77560080401dc3817830ae6bb985cf680d5dd6d7cf60a362cb6851435f50366e",
          "sha256": "7ce0850f0233cbab6d3722caedbacb7f26ed26fad1104924875cf9864462999d",
          "sha1": "0f5aaf12955b79e531f919602d9ef3cf6353ae98",
          "md5": "8071396f459ff5ef02aa16389635a80a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.13.aar",
          "url": "gamepad-0.0.13.aar",
          "size": 8844630,
          "sha512": "3e70a580b5536084ea199a1b262c669c0189dab06dd3ae83f53b82fb1391206f77560080401dc3817830ae6bb985cf680d5dd6d7cf60a362cb6851435f50366e",
          "sha256": "7ce0850f0233cbab6d3722caedbacb7f26ed26fad1104924875cf9864462999d",
          "sha1": "0f5aaf12955b79e531f919602d9ef3cf6353ae98",
          "md5": "8071396f459ff5ef02aa16389635a80a"
        }
      ]
    }
  ]
}
