{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "gamepad",
    "version": "0.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.13.aar",
          "url": "gamepad-0.0.13.aar",
          "size": 8844646,
          "sha512": "478888f7033506ebbd94f90934382d4feaaa03d3145eb88d4579f11f6dbed88fa0d646a597ea5af376ff7ff7790482875ada4d75d0874922534e2931eb5807f5",
          "sha256": "f0a247899d9f089eabb8f60e4d057c19728d0ef31479774208e3fdbdc9f61064",
          "sha1": "cb5828803badc7296ca6807e8722e7999537fea7",
          "md5": "05b7c1e8c135db381bdf452efe12895f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "gamepad-0.0.13.aar",
          "url": "gamepad-0.0.13.aar",
          "size": 8844646,
          "sha512": "478888f7033506ebbd94f90934382d4feaaa03d3145eb88d4579f11f6dbed88fa0d646a597ea5af376ff7ff7790482875ada4d75d0874922534e2931eb5807f5",
          "sha256": "f0a247899d9f089eabb8f60e4d057c19728d0ef31479774208e3fdbdc9f61064",
          "sha1": "cb5828803badc7296ca6807e8722e7999537fea7",
          "md5": "05b7c1e8c135db381bdf452efe12895f"
        }
      ]
    }
  ]
}
