{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "opmodecontrol",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.10.aar",
          "url": "opmodecontrol-0.0.10.aar",
          "size": 905193,
          "sha512": "2c78e766faa9df438b285b4857db40ac471bcff569274bbcdf8ce9f002559024e6c1901173977d3d52a8610a7aa8383938d79f4468df3c2a1901384be1fb971c",
          "sha256": "842508d6dc30ff375f1fda5a6162d63dcab6efb56fdf4633ec6713dda71146eb",
          "sha1": "00204f5d75db24730a3cb51177f430c0f0d93257",
          "md5": "ff91dfa9356bd262726bde1b5d8ac3d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.10.aar",
          "url": "opmodecontrol-0.0.10.aar",
          "size": 905193,
          "sha512": "2c78e766faa9df438b285b4857db40ac471bcff569274bbcdf8ce9f002559024e6c1901173977d3d52a8610a7aa8383938d79f4468df3c2a1901384be1fb971c",
          "sha256": "842508d6dc30ff375f1fda5a6162d63dcab6efb56fdf4633ec6713dda71146eb",
          "sha1": "00204f5d75db24730a3cb51177f430c0f0d93257",
          "md5": "ff91dfa9356bd262726bde1b5d8ac3d9"
        }
      ]
    }
  ]
}
