{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "opmodecontrol",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.10.aar",
          "url": "opmodecontrol-0.0.10.aar",
          "size": 905177,
          "sha512": "7ba8b286ff3791ed098f7b58541af82e91aaa72e22cbf3dbbdacefda7647ca4568c1bbc50f21a05825032a1c0d62f8e4371ba165fae1285324eab23115ba29ca",
          "sha256": "0de1cbcba54b57657f9b5cd7993e0a87076c949c080c112910d0b2b0c0c17e24",
          "sha1": "48631559b8f7e9e36df3c59073314d25867faab3",
          "md5": "8c2ad099fef17672e5bd5fff1730f001"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "opmodecontrol-0.0.10.aar",
          "url": "opmodecontrol-0.0.10.aar",
          "size": 905177,
          "sha512": "7ba8b286ff3791ed098f7b58541af82e91aaa72e22cbf3dbbdacefda7647ca4568c1bbc50f21a05825032a1c0d62f8e4371ba165fae1285324eab23115ba29ca",
          "sha256": "0de1cbcba54b57657f9b5cd7993e0a87076c949c080c112910d0b2b0c0c17e24",
          "sha1": "48631559b8f7e9e36df3c59073314d25867faab3",
          "md5": "8c2ad099fef17672e5bd5fff1730f001"
        }
      ]
    }
  ]
}
