{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-0.0.0.aar",
          "url": "pedro-0.0.0.aar",
          "size": 756,
          "sha512": "31fbaf8f1721668bd48d83e53cb997128558a0f69e6dedef4a9731c879b0a1c758cc0fdae798ea3580938f094ae2b633bbbdf5eec0dc163b9cb5422d769f9f39",
          "sha256": "b5ce7f004b8a1978e56c414b740e28c85501ea257ef9a0c834c8632aabb4db17",
          "sha1": "b9dd70a474aec567b224ab70965d302dc8011ea7",
          "md5": "58f60df76c922aca6ab9729310669e9a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.0.0.aar",
          "url": "pedro-0.0.0.aar",
          "size": 756,
          "sha512": "31fbaf8f1721668bd48d83e53cb997128558a0f69e6dedef4a9731c879b0a1c758cc0fdae798ea3580938f094ae2b633bbbdf5eec0dc163b9cb5422d769f9f39",
          "sha256": "b5ce7f004b8a1978e56c414b740e28c85501ea257ef9a0c834c8632aabb4db17",
          "sha1": "b9dd70a474aec567b224ab70965d302dc8011ea7",
          "md5": "58f60df76c922aca6ab9729310669e9a"
        }
      ]
    }
  ]
}
