{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "field",
    "version": "0.0.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.11.aar",
          "url": "field-0.0.11.aar",
          "size": 1103644,
          "sha512": "3ccaeea9f2236076e24da2d98ee724e5698d3d9400b4bab4d226175652f3dbbe90b8ea8129ae5560c2d3513535bcdb28092dbb92e4ae1b274c9731b0732a681f",
          "sha256": "63d48f81537f5732f47da068fbb7a8b1c76dc221a2df82e83cdd511bc33abdf0",
          "sha1": "e396bfe23ff8c1b5abcbebf7970b6b4fcce6b60d",
          "md5": "9a3b4e5986c6225fc179ebbc8842f06f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "field-0.0.11.aar",
          "url": "field-0.0.11.aar",
          "size": 1103644,
          "sha512": "3ccaeea9f2236076e24da2d98ee724e5698d3d9400b4bab4d226175652f3dbbe90b8ea8129ae5560c2d3513535bcdb28092dbb92e4ae1b274c9731b0732a681f",
          "sha256": "63d48f81537f5732f47da068fbb7a8b1c76dc221a2df82e83cdd511bc33abdf0",
          "sha1": "e396bfe23ff8c1b5abcbebf7970b6b4fcce6b60d",
          "md5": "9a3b4e5986c6225fc179ebbc8842f06f"
        }
      ]
    }
  ]
}
