{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "beta",
    "version": "1.0.8-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "beta-1.0.8-beta1.aar",
          "url": "beta-1.0.8-beta1.aar",
          "size": 89520,
          "sha512": "44056297d3c8b83c7fdd2ab2523a3608a429151365cd6b017e64c8565bc3cd824285621a47df703d2e0ebb860d91dd7cd229c9bb5f2fc3f287eea8d026ba523b",
          "sha256": "d60aef7530cffa608f0fc5d5754207c08da7c7ff718e86a9685c1ca932d3317b",
          "sha1": "b062adb23e19c4198250527feb617eb478917058",
          "md5": "7173bd1864f317da6fdd98cf98dd7092"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "beta-1.0.8-beta1.aar",
          "url": "beta-1.0.8-beta1.aar",
          "size": 89520,
          "sha512": "44056297d3c8b83c7fdd2ab2523a3608a429151365cd6b017e64c8565bc3cd824285621a47df703d2e0ebb860d91dd7cd229c9bb5f2fc3f287eea8d026ba523b",
          "sha256": "d60aef7530cffa608f0fc5d5754207c08da7c7ff718e86a9685c1ca932d3317b",
          "sha1": "b062adb23e19c4198250527feb617eb478917058",
          "md5": "7173bd1864f317da6fdd98cf98dd7092"
        }
      ]
    }
  ]
}
