{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "telemetry",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "telemetry-0.0.6.aar",
          "url": "telemetry-0.0.6.aar",
          "size": 9205,
          "sha512": "6fca39872ba6b145f3c21ccbe87ec682e661d9961ec29e45a205e317b44c69e6b9cc1872e429f1e85c066bb7561108d1f5e3822ebf3d935e1ae8f0f06bc66a6b",
          "sha256": "37aaaaaab5f6469eb87e24509bcf6408b0f6aa910851457baf62bb6d1c40f6a5",
          "sha1": "122907e46d5ca479df6da8acd8e4fd95ac9110bc",
          "md5": "a366d4cc6fc33593d81a625fa0f8e1d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "telemetry-0.0.6.aar",
          "url": "telemetry-0.0.6.aar",
          "size": 9205,
          "sha512": "6fca39872ba6b145f3c21ccbe87ec682e661d9961ec29e45a205e317b44c69e6b9cc1872e429f1e85c066bb7561108d1f5e3822ebf3d935e1ae8f0f06bc66a6b",
          "sha256": "37aaaaaab5f6469eb87e24509bcf6408b0f6aa910851457baf62bb6d1c40f6a5",
          "sha1": "122907e46d5ca479df6da8acd8e4fd95ac9110bc",
          "md5": "a366d4cc6fc33593d81a625fa0f8e1d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "telemetry-0.0.6-sources.jar",
          "url": "telemetry-0.0.6-sources.jar",
          "size": 4796,
          "sha512": "78a0b2c3652afbf74eb9b8ba2613e0aa1daaa4f7a8eca39fa910a91fcb849fcbd0ee2ce869f1a6b011bf6338885e085510c627a0080f7e740c0d0814020bc3ff",
          "sha256": "07407c20c33607e8c3d1528e1b374358e66008d4a3749b32443018dd6fe34811",
          "sha1": "fa8fd9971cc19d99b956ab6d1632a5392e5b25a9",
          "md5": "a1cef7380a45c630392569e53573efdb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "telemetry-0.0.6-javadoc.jar",
          "url": "telemetry-0.0.6-javadoc.jar",
          "size": 297798,
          "sha512": "3f438b9b37fec9a50a50999f5872639d3b3f17affef435b6775704c331e0091e20e8e8bd0d8c37a9fb2255b9785c8317745bda3319eeb57c8b7fa27156ff0e16",
          "sha256": "cf6f1c3e56806c5ee543a8395d785bde74bd4626cf4266cdc9d8458ef69332ec",
          "sha1": "094623c6db14911f915b630825fe86a056801be5",
          "md5": "720ddc4f1141197c310d727410f53b8f"
        }
      ]
    }
  ]
}
