{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing.panels",
    "module": "utils",
    "version": "0.0.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.10.aar",
          "url": "utils-0.0.10.aar",
          "size": 1403976,
          "sha512": "42a10a2554a6214f0b21c7a074c05fcdc289149447ae0ebdabae855c4d835daf7137b0ef7a2d49ec7234f71396357f4afaf33b7b27645246a4a57d13aac249bb",
          "sha256": "29443a7849c21bade73fa6658d2101e371fd71e275e3de7791d4d430dad95f12",
          "sha1": "478650ea2f34dc48997b7daa7a244c3f1914defa",
          "md5": "10470e5dd5e0a3f76b60b133a8b0eab1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.0.10.aar",
          "url": "utils-0.0.10.aar",
          "size": 1403976,
          "sha512": "42a10a2554a6214f0b21c7a074c05fcdc289149447ae0ebdabae855c4d835daf7137b0ef7a2d49ec7234f71396357f4afaf33b7b27645246a4a57d13aac249bb",
          "sha256": "29443a7849c21bade73fa6658d2101e371fd71e275e3de7791d4d430dad95f12",
          "sha1": "478650ea2f34dc48997b7daa7a244c3f1914defa",
          "md5": "10470e5dd5e0a3f76b60b133a8b0eab1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.0.10-sources.jar",
          "url": "utils-0.0.10-sources.jar",
          "size": 2208,
          "sha512": "42ea2f4380d701e09e36f1fe1f4ac9c8bf5f3c2a1c4b35de9139bf26028ce0e776a2248783b770380bbc58fc64420bababbeeba799208fa2cdeca787d909657a",
          "sha256": "803e05df6a89961bf082cade955d6ed344ecffa5c75501106019e099fe40c0ca",
          "sha1": "0f1092b136db253b795648556d4af6c1f95bbde2",
          "md5": "11c8ed514056c3fde9a4fa1cfd0b9534"
        }
      ]
    }
  ]
}
