{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-1.1.0-SNAPSHOT.jar",
          "url": "pedro-1.1.0-SNAPSHOT.jar",
          "size": 85709,
          "sha512": "223d2461ff69aa53622ca126500da80d945e939000db8f0a50cc6eb283c6d1fc4f751e56e858df0bc487ed677f646cc81513c1e5a9c8fc0d74e2bc613a96e93b",
          "sha256": "9de868b92ae7cf20f2c69edcbdfe0e446fa4140a0decd020476cba9767984adc",
          "sha1": "e39f21fe9a137e0e60dcb9bfda06688b32fc98e4",
          "md5": "041dc3d857c3ae4d9e82a769b58db7ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pedro-1.1.0-SNAPSHOT.jar",
          "url": "pedro-1.1.0-SNAPSHOT.jar",
          "size": 85709,
          "sha512": "223d2461ff69aa53622ca126500da80d945e939000db8f0a50cc6eb283c6d1fc4f751e56e858df0bc487ed677f646cc81513c1e5a9c8fc0d74e2bc613a96e93b",
          "sha256": "9de868b92ae7cf20f2c69edcbdfe0e446fa4140a0decd020476cba9767984adc",
          "sha1": "e39f21fe9a137e0e60dcb9bfda06688b32fc98e4",
          "md5": "041dc3d857c3ae4d9e82a769b58db7ab"
        }
      ]
    }
  ]
}
