{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-1.1.0-SNAPSHOT.jar",
          "url": "pedro-1.1.0-SNAPSHOT.jar",
          "size": 84889,
          "sha512": "777b91ef2c1daa9c03229c71e1ee4fcc085ef22c28f888c07e91c68c3965fd31478356e91882b8e6f2f28550665f710ccd127e0d0d97d102d4bfdbd3a17ffbaf",
          "sha256": "ec50f854d44c9941d5128d599a7b9777558d6e155ffea2ded2eb9650c0d7c4af",
          "sha1": "c6667322c179c4b5dfc5b6d5b2c7af31d7241387",
          "md5": "0e0ebb1eaa77ac8bf93a76f81d5d5253"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 22,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pedro-1.1.0-SNAPSHOT.jar",
          "url": "pedro-1.1.0-SNAPSHOT.jar",
          "size": 84889,
          "sha512": "777b91ef2c1daa9c03229c71e1ee4fcc085ef22c28f888c07e91c68c3965fd31478356e91882b8e6f2f28550665f710ccd127e0d0d97d102d4bfdbd3a17ffbaf",
          "sha256": "ec50f854d44c9941d5128d599a7b9777558d6e155ffea2ded2eb9650c0d7c4af",
          "sha1": "c6667322c179c4b5dfc5b6d5b2c7af31d7241387",
          "md5": "0e0ebb1eaa77ac8bf93a76f81d5d5253"
        }
      ]
    }
  ]
}
