{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "1.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-1.1.0-SNAPSHOT.jar",
          "url": "pedro-1.1.0-SNAPSHOT.jar",
          "size": 89542,
          "sha512": "261cc20df5f0fb0f1da58e37d1b6c87dd65e80dc7e10d581505e9a329b4414b889586348083629f252b7ccbc95c95e595f7bfe473c8ab5c9a4af670903927c84",
          "sha256": "9a8f6d3ac4a3bf046ea158109dc689c6508a52e1a3f7b846539be84dd6c3d88f",
          "sha1": "86233121dd6bcc04753ad353e2c64b8a56b825a8",
          "md5": "49ae1d05b3b5dfc6757e56425d7da720"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 23,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pedro-1.1.0-SNAPSHOT.jar",
          "url": "pedro-1.1.0-SNAPSHOT.jar",
          "size": 89542,
          "sha512": "261cc20df5f0fb0f1da58e37d1b6c87dd65e80dc7e10d581505e9a329b4414b889586348083629f252b7ccbc95c95e595f7bfe473c8ab5c9a4af670903927c84",
          "sha256": "9a8f6d3ac4a3bf046ea158109dc689c6508a52e1a3f7b846539be84dd6c3d88f",
          "sha1": "86233121dd6bcc04753ad353e2c64b8a56b825a8",
          "md5": "49ae1d05b3b5dfc6757e56425d7da720"
        }
      ]
    }
  ]
}
