{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "pedro",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pedro-1.0.1.aar",
          "url": "pedro-1.0.1.aar",
          "size": 86560,
          "sha512": "894546a88df956997211fd3d0d34897953dccf9554f7795588f880e1a523bd624f0b690518b48c9a4e8935921178c2386fe751c2b21d68f200a5881afbddb488",
          "sha256": "38ecac2b96e3e9ae1821984f89cee355fe6d634fc4a2626da0e5597847243944",
          "sha1": "795b81c130c9de378dcfbe408776fc29d558c936",
          "md5": "102e2d62b2600d381b1e23b645500421"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-1.0.1.aar",
          "url": "pedro-1.0.1.aar",
          "size": 86560,
          "sha512": "894546a88df956997211fd3d0d34897953dccf9554f7795588f880e1a523bd624f0b690518b48c9a4e8935921178c2386fe751c2b21d68f200a5881afbddb488",
          "sha256": "38ecac2b96e3e9ae1821984f89cee355fe6d634fc4a2626da0e5597847243944",
          "sha1": "795b81c130c9de378dcfbe408776fc29d558c936",
          "md5": "102e2d62b2600d381b1e23b645500421"
        }
      ]
    }
  ]
}
