{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "ftc",
    "version": "1.1.0-SNAPSHOTT",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "core",
          "version": {
            "requires": "1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOTT.aar",
          "url": "ftc-1.1.0-SNAPSHOTT.aar",
          "size": 37761,
          "sha512": "ee243c1a6c76c78625a98c929dc0a6d0f7e2806bc63246e2e3fabbaae1c6bcea745eace1a035f9d0c42b3ee15820524b4e89f792b92cdd08624f642aabe27380",
          "sha256": "9f6439e872d85d165181f1b30250e6f32a0119465c0d2044428c9533c16d153b",
          "sha1": "747356ce199655887ad1822f582d2650c3c4f662",
          "md5": "088ad04ccbf3bad12d0be54795b06644"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "core",
          "version": {
            "requires": "1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOTT.aar",
          "url": "ftc-1.1.0-SNAPSHOTT.aar",
          "size": 37761,
          "sha512": "ee243c1a6c76c78625a98c929dc0a6d0f7e2806bc63246e2e3fabbaae1c6bcea745eace1a035f9d0c42b3ee15820524b4e89f792b92cdd08624f642aabe27380",
          "sha256": "9f6439e872d85d165181f1b30250e6f32a0119465c0d2044428c9533c16d153b",
          "sha1": "747356ce199655887ad1822f582d2650c3c4f662",
          "md5": "088ad04ccbf3bad12d0be54795b06644"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOTT-sources.jar",
          "url": "ftc-1.1.0-SNAPSHOTT-sources.jar",
          "size": 33848,
          "sha512": "1fbfd70db635ba6cef8945fe2d1067f3b6c46ab9a2d122c02fd56e35d1ce5df90be8eb9701e37fe88fa325045242b472d12373b0f64c3e12cc3ce8e98085e921",
          "sha256": "2f9bbb5e536a7e06baf64d416ed8acb9409509bd12a706bb0a4b33acd9845aa4",
          "sha1": "2ab7e1eccd7ca144c5711b87ed50ba496dcf5dbd",
          "md5": "c2753fa3f82e8fc2da220d9d935153b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOTT-javadoc.jar",
          "url": "ftc-1.1.0-SNAPSHOTT-javadoc.jar",
          "size": 401672,
          "sha512": "68795609eb066bdd16ef8f3afbb947297304c54d1818571ac3ee112f1b644a1977c63494b4574fa3930f550c8d02f487cd0dc0f88fde460c1c958de03ba3f4ad",
          "sha256": "701a18374c42fb764dd8c5f08b6940eb1537c34c932a853eb6d76ddf30e10dd6",
          "sha1": "0798295006aaa4f004641a178c8041ee6353fc67",
          "md5": "f78a14b3d618ee8d8bac393cbdd87545"
        }
      ]
    }
  ]
}
