{
  "formatVersion": "1.1",
  "component": {
    "group": "com.pedropathing",
    "module": "ftc",
    "version": "1.1.0-SNAPSHOTT",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "core",
          "version": {
            "requires": "1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOTT.aar",
          "url": "ftc-1.1.0-SNAPSHOTT.aar",
          "size": 37729,
          "sha512": "5053f859ca1c4acdd335f49467c1cdd3d3bb8cc69f1ea6e32d16a777b041437ba6c7f29acc7d2f49c28c051e8ddb06d9cf03153b68dc79553a1dd1e44d1ae22a",
          "sha256": "cda8bd84d97c3c8e87a93f786907f5718be614ed94f5af47953f7d8b498d98b1",
          "sha1": "3db199dce56442a8123bd17b69ee4dbbfa1837db",
          "md5": "d851d98f815de9891f4d0ce69b3ca268"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.pedropathing",
          "module": "core",
          "version": {
            "requires": "1.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOTT.aar",
          "url": "ftc-1.1.0-SNAPSHOTT.aar",
          "size": 37729,
          "sha512": "5053f859ca1c4acdd335f49467c1cdd3d3bb8cc69f1ea6e32d16a777b041437ba6c7f29acc7d2f49c28c051e8ddb06d9cf03153b68dc79553a1dd1e44d1ae22a",
          "sha256": "cda8bd84d97c3c8e87a93f786907f5718be614ed94f5af47953f7d8b498d98b1",
          "sha1": "3db199dce56442a8123bd17b69ee4dbbfa1837db",
          "md5": "d851d98f815de9891f4d0ce69b3ca268"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOTT-sources.jar",
          "url": "ftc-1.1.0-SNAPSHOTT-sources.jar",
          "size": 33848,
          "sha512": "1fbfd70db635ba6cef8945fe2d1067f3b6c46ab9a2d122c02fd56e35d1ce5df90be8eb9701e37fe88fa325045242b472d12373b0f64c3e12cc3ce8e98085e921",
          "sha256": "2f9bbb5e536a7e06baf64d416ed8acb9409509bd12a706bb0a4b33acd9845aa4",
          "sha1": "2ab7e1eccd7ca144c5711b87ed50ba496dcf5dbd",
          "md5": "c2753fa3f82e8fc2da220d9d935153b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ftc-1.1.0-SNAPSHOTT-javadoc.jar",
          "url": "ftc-1.1.0-SNAPSHOTT-javadoc.jar",
          "size": 401672,
          "sha512": "68795609eb066bdd16ef8f3afbb947297304c54d1818571ac3ee112f1b644a1977c63494b4574fa3930f550c8d02f487cd0dc0f88fde460c1c958de03ba3f4ad",
          "sha256": "701a18374c42fb764dd8c5f08b6940eb1537c34c932a853eb6d76ddf30e10dd6",
          "sha1": "0798295006aaa4f004641a178c8041ee6353fc67",
          "md5": "f78a14b3d618ee8d8bac393cbdd87545"
        }
      ]
    }
  ]
}
